# Generated by Django 4.1.5 on 2023-01-29 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('ALABAMA', 'Alabama'), ('ALASKA', 'Alaska'), ('ARIZONA', 'Arizona'), ('ARKANSAS', 'Arkansas'), ('CALIFORNIA', 'California'), ('COLORADO', 'Colorado'), ('CONNECTICUT', 'Connecticut'), ('DELAWARE', 'Delaware'), ('FLORIDA', 'Florida'), ('GEORGIA', 'Georgia'), ('HAWAII', 'Hawaii'), ('IDAHO', 'Idaho'), ('ILLINOIS', 'Illinois'), ('INDIANA', 'Indiana'), ('IOWA', 'Iowa'), ('KANSAS', 'Kansas'), ('KENTUCKY', 'Kentucky'), ('LOUISIANA', 'Louisiana'), ('MAINE', 'Maine'), ('MARYLAND', 'Maryland'), ('MASSACHUSETTS', 'Massachusetts'), ('MICHIGAN', 'Michigan'), ('MINNESOTA', 'Minnesota'), ('MISSISSIPPI', 'Mississippi'), ('MISSOURI', 'Missouri'), ('MONTANA', 'Montana'), ('NEBRASKA', 'Nebraska'), ('NEVADA', 'Nevada'), ('NEW_HAMPSHIRE', 'New Hampshire'), ('NEW_JERSEY', 'New Jersey'), ('NEW_MEXICO', 'New Mexico'), ('NEW_YORK', 'New York'), ('NORTH_CAROLINA', 'North Carolina'), ('NORTH_DAKOTA', 'North Dakota'), ('OHIO', 'Ohio'), ('OKLAHOMA', 'Oklahoma'), ('OREGON', 'Oregon'), ('PENNSYLVANIA', 'Pennsylvania'), ('RHODE_ISLAND', 'Rhode Island'), ('SOUTH_CAROLINA', 'South Carolina'), ('SOUTH_DAKOTA', 'South Dakota'), ('TENNESSEE', 'Tennessee'), ('TEXAS', 'Texas'), ('UTAH', 'Utah'), ('VERMONT', 'Vermont'), ('VIRGINIA', 'Virginia'), ('WASHINGTON', 'Washington'), ('WEST_VIRGINIA', 'West Virginia'), ('WISCONSIN', 'Wisconsin'), ('WYOMING', 'Wyoming')], default='CALIFORNIA', max_length=100, null=True)),
                ('rent', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('building', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_date', models.DateTimeField(blank=True, null=True)),
                ('move_in_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rental')),
            ],
        ),
    ]
