# Generated by Django 4.1.5 on 2023-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tour_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/<built-in function id>/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/<built-in function id>/'),
        ),
        migrations.AddField(
            model_name='rental',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/<built-in function id>/'),
        ),
    ]
