# Generated by Django 4.1.5 on 2023-02-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rental'),
        ),
    ]
